[package]
name = "defund-cosmwasm"
version = "0.1.1"
edition = "2021"
description = "Bindings for Cosmwasm on the Defund blockchain."
license = "Apache-2.0"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
serde_repr = "0.1.8"
protobuf = { version = "=3.2.0", features = ["with-bytes"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"